# Generated by Django 2.1.2 on 2020-05-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200520_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('4', '4'), ('2', '2')], max_length=1),
        ),
    ]
