# Generated by Django 2.1.2 on 2020-05-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200523_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('3', '3'), ('4', '4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(choices=[('IS', 'IS'), ('RET', 'RET'), ('CSSE', 'CSSE')], max_length=12),
        ),
    ]
