# Generated by Django 2.1.2 on 2020-05-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200523_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(choices=[('RET', 'RET'), ('IS', 'IS'), ('CSSE', 'CSSE')], max_length=12),
        ),
    ]
