# Generated by Django 2.1.2 on 2020-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200523_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('3', '3'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(choices=[('IS', 'IS'), ('RET', 'RET'), ('CSSE', 'CSSE')], max_length=12),
        ),
    ]
