# Generated by Django 2.1.2 on 2020-05-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200524_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('4', '4'), ('1', '1'), ('3', '3'), ('2', '2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(choices=[('IS', 'IS'), ('CSSE', 'CSSE'), ('RET', 'RET')], max_length=12),
        ),
    ]
