# Generated by Django 2.1.2 on 2020-05-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200527_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('4', '4'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(choices=[('CSSE', 'CSSE'), ('RET', 'RET'), ('IS', 'IS')], max_length=12),
        ),
    ]
