# Generated by Django 2.1.2 on 2020-05-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200531_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(choices=[('CSSE', 'CSSE'), ('RET', 'RET'), ('IS', 'IS')], max_length=12),
        ),
    ]
