# Generated by Django 2.1.2 on 2020-05-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200531_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='сс_approve',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(choices=[('CSSE', 'CSSE'), ('RET', 'RET'), ('IS', 'IS')], max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='сс_approve',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1, null=True),
        ),
    ]
