# Generated by Django 2.1.2 on 2020-06-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20200601_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('1', '1'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(choices=[('IS', 'IS'), ('RET', 'RET'), ('CSSE', 'CSSE')], max_length=12),
        ),
    ]
