# Generated by Django 2.1.2 on 2020-06-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20200605_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='сс_approve',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('2', '2'), ('4', '4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='сс_approve',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=1, null=True),
        ),
    ]
