# Generated by Django 2.1.2 on 2020-06-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20200606_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='сс_approve',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('4', '4'), ('2', '2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(choices=[('RET', 'RET'), ('CSSE', 'CSSE'), ('IS', 'IS')], max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='сс_approve',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1, null=True),
        ),
    ]
