# Generated by Django 2.1.2 on 2020-05-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('adv_id', models.AutoField(primary_key=True, serialize=False)),
                ('Advice', models.CharField(max_length=24)),
                ('render', models.BooleanField(default=False)),
            ],
        ),
    ]
