# Generated by Django 2.1.2 on 2020-05-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_override', '0002_advice_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_help_type', models.CharField(max_length=24)),
                ('answer_question', models.CharField(max_length=24)),
                ('answer', models.CharField(max_length=24)),
                ('render', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=24)),
                ('about_author', models.CharField(max_length=512)),
                ('Theme', models.TextField()),
                ('Article', models.TextField()),
                ('Article_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes', models.CharField(max_length=24)),
                ('content', models.CharField(max_length=24)),
                ('sent_name', models.CharField(max_length=24)),
                ('e_mail', models.CharField(max_length=24)),
            ],
        ),
        migrations.AlterField(
            model_name='advice',
            name='photo',
            field=models.ImageField(upload_to='admin_override/uploads/'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='render',
            field=models.BooleanField(default=True),
        ),
    ]
