# Generated by Django 2.1.2 on 2020-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_override', '0004_auto_20200524_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.TextField(),
        ),
    ]
