# Generated by Django 2.1.2 on 2020-05-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_override', '0006_auto_20200524_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='Advice',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_help_type',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='article',
            name='Author',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='e_mail',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sent_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='topic',
            field=models.CharField(max_length=512),
        ),
    ]
