# Generated by Django 2.1.2 on 2020-05-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_override', '0007_auto_20200524_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(),
        ),
    ]
