# Generated by Django 2.1.2 on 2020-05-25 18:19

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200526_0019'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='employer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Employer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_mail',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contacts_site',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.TextField(null=True),
        ),
    ]
