# Generated by Django 2.1.2 on 2020-05-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200527_1910'),
        ('employer', '0003_auto_20200526_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('resp_id', models.AutoField(primary_key=True, serialize=False)),
                ('approve', models.BooleanField()),
                ('send_date', models.DateField(auto_now=True)),
                ('message', models.TextField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
                ('vac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Vacancy')),
            ],
        ),
    ]
