# Generated by Django 2.1.2 on 2020-05-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_auto_20200530_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='respond',
            name='respond_status_employer',
            field=models.CharField(choices=[('2', 'Resume viewed'), ('3', 'Renouncement'), ('1', 'Resume not viewed')], max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='respond',
            name='respond_status_student',
            field=models.CharField(choices=[('2', 'Resume viewed'), ('3', 'Renouncement'), ('1', 'Resume not viewed')], max_length=512, null=True),
        ),
    ]
