# Generated by Django 2.1.2 on 2020-05-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_auto_20200531_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='respond',
            name='respond_send_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='respond',
            name='respond_status_employer',
            field=models.CharField(choices=[('2', 'Resume viewed'), ('1', 'Resume not viewed'), ('3', 'Renouncement')], max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='respond',
            name='respond_status_student',
            field=models.CharField(choices=[('2', 'Resume viewed'), ('1', 'Resume not viewed'), ('3', 'Renouncement')], max_length=512, null=True),
        ),
    ]
