# Generated by Django 2.1.2 on 2020-05-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_auto_20200531_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respond',
            name='respond_status_employer',
            field=models.CharField(choices=[('1', 'Resume not viewed'), ('3', 'Renouncement'), ('2', 'Resume viewed')], max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='respond',
            name='respond_status_student',
            field=models.CharField(choices=[('1', 'Resume not viewed'), ('3', 'Renouncement'), ('2', 'Resume viewed')], default='Resume not viewed', max_length=512),
        ),
    ]
