# Generated by Django 2.1.2 on 2020-05-20 17:48

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_auto_20160213_1726'),
        ('student', '0003_personalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(max_length=30, null=True)),
                ('home_phone', models.CharField(max_length=30, null=True)),
                ('skype', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesiredPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_position', models.CharField(max_length=30, null=True)),
                ('professional_area', models.CharField(max_length=30, null=True)),
                ('employment', models.CharField(choices=[('Internship', 'Internship'), ('Part-time employment', 'Part-time employment'), ('Project work', 'Project work'), ('Full employment', 'Full employment'), ('Volunteering', 'Volunteering')], max_length=100)),
                ('schedule', models.CharField(choices=[('Full day', 'Full day'), ('Shift method', 'Shift method'), ('Remote work', 'Remote work'), ('Flexible schedule', 'Flexible schedule'), ('Shift work', 'Shift work')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100, null=True)),
                ('course', models.CharField(max_length=100, null=True)),
                ('specality', models.CharField(max_length=100, null=True)),
                ('date_of_ending', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getting_started_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organization', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('workplace_respon', models.TextField()),
                ('key_skills', models.CharField(max_length=100, null=True)),
                ('region', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_language', models.CharField(max_length=100, null=True)),
                ('second_language', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=12),
        ),
    ]
