# Generated by Django 2.1.2 on 2020-05-22 20:11

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200523_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstudent',
            name='about_student',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(choices=[('Full employment', 'Full employment'), ('Internship', 'Internship'), ('Volunteering', 'Volunteering'), ('Project work', 'Project work'), ('Part-time employment', 'Part-time employment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(choices=[('Shift work', 'Shift work'), ('Full day', 'Full day'), ('Flexible schedule', 'Flexible schedule'), ('Shift method', 'Shift method'), ('Remote work', 'Remote work')], max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_of_ending',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='region',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
