# Generated by Django 2.1.2 on 2020-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200523_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(choices=[('Part-time employment', 'Part-time employment'), ('Volunteering', 'Volunteering'), ('Full employment', 'Full employment'), ('Internship', 'Internship'), ('Project work', 'Project work')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(choices=[('Shift method', 'Shift method'), ('Shift work', 'Shift work'), ('Full day', 'Full day'), ('Remote work', 'Remote work'), ('Flexible schedule', 'Flexible schedule')], max_length=100),
        ),
    ]
