# Generated by Django 2.1.2 on 2020-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200523_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(choices=[('Project work', 'Project work'), ('Part-time employment', 'Part-time employment'), ('Internship', 'Internship'), ('Full employment', 'Full employment'), ('Volunteering', 'Volunteering')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(choices=[('Full day', 'Full day'), ('Shift method', 'Shift method'), ('Shift work', 'Shift work'), ('Remote work', 'Remote work'), ('Flexible schedule', 'Flexible schedule')], max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='getting_started_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='workplace_respon',
            field=models.TextField(null=True),
        ),
    ]
