# Generated by Django 2.1.2 on 2020-05-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20200523_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Full employment', 'Full employment'), ('Volunteering', 'Volunteering'), ('Project work', 'Project work'), ('Part-time employment', 'Part-time employment'), ('Internship', 'Internship')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Full day', 'Full day'), ('Shift method', 'Shift method'), ('Shift work', 'Shift work'), ('Flexible schedule', 'Flexible schedule'), ('Remote work', 'Remote work')], max_length=100),
        ),
    ]
