# Generated by Django 2.1.2 on 2020-05-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200523_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Full employment', 'Full employment'), ('Volunteering', 'Volunteering'), ('Project work', 'Project work'), ('Part-time employment', 'Part-time employment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Flexible schedule', 'Flexible schedule'), ('Full day', 'Full day'), ('Shift work', 'Shift work'), ('Remote work', 'Remote work'), ('Shift method', 'Shift method')], max_length=100),
        ),
    ]
