# Generated by Django 2.1.2 on 2020-05-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20200524_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Volunteering', 'Volunteering'), ('Part-time employment', 'Part-time employment'), ('Full employment', 'Full employment'), ('Internship', 'Internship'), ('Project work', 'Project work')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Flexible schedule', 'Flexible schedule'), ('Full day', 'Full day'), ('Shift work', 'Shift work'), ('Shift method', 'Shift method'), ('Remote work', 'Remote work')], max_length=100),
        ),
    ]
