# Generated by Django 2.1.2 on 2020-05-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20200524_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Volunteering', 'Volunteering'), ('Part-time employment', 'Part-time employment'), ('Full employment', 'Full employment'), ('Project work', 'Project work'), ('Internship', 'Internship')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Remote work', 'Remote work'), ('Full day', 'Full day'), ('Flexible schedule', 'Flexible schedule'), ('Shift method', 'Shift method'), ('Shift work', 'Shift work')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=12, null=True),
        ),
    ]
