# Generated by Django 2.1.2 on 2020-05-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20200524_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Project work', 'Project work'), ('Internship', 'Internship'), ('Full employment', 'Full employment'), ('Part-time employment', 'Part-time employment'), ('Volunteering', 'Volunteering')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Full day', 'Full day'), ('Remote work', 'Remote work'), ('Shift work', 'Shift work'), ('Flexible schedule', 'Flexible schedule'), ('Shift method', 'Shift method')], max_length=100),
        ),
    ]
