# Generated by Django 2.1.2 on 2020-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20200524_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Volunteering', 'Volunteering'), ('Project work', 'Project work'), ('Part-time employment', 'Part-time employment'), ('Full employment', 'Full employment'), ('Internship', 'Internship')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Remote work', 'Remote work'), ('Shift work', 'Shift work'), ('Shift method', 'Shift method'), ('Full day', 'Full day'), ('Flexible schedule', 'Flexible schedule')], max_length=100),
        ),
    ]
