# Generated by Django 2.1.2 on 2020-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20200524_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Volunteering', 'Volunteering'), ('Full employment', 'Full employment'), ('Part-time employment', 'Part-time employment'), ('Project work', 'Project work')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Shift method', 'Shift method'), ('Full day', 'Full day'), ('Shift work', 'Shift work'), ('Remote work', 'Remote work'), ('Flexible schedule', 'Flexible schedule')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=12, null=True),
        ),
    ]
