# Generated by Django 2.1.2 on 2020-05-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20200524_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Full employment', 'Full employment'), ('Part-time employment', 'Part-time employment'), ('Project work', 'Project work'), ('Volunteering', 'Volunteering'), ('Internship', 'Internship')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Remote work', 'Remote work'), ('Full day', 'Full day'), ('Shift work', 'Shift work'), ('Shift method', 'Shift method'), ('Flexible schedule', 'Flexible schedule')], max_length=100),
        ),
    ]
