# Generated by Django 2.1.2 on 2020-05-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20200526_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Project work', 'Project work'), ('Volunteering', 'Volunteering'), ('Internship', 'Internship'), ('Full employment', 'Full employment'), ('Part-time employment', 'Part-time employment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Remote work', 'Remote work'), ('Full day', 'Full day'), ('Flexible schedule', 'Flexible schedule'), ('Shift method', 'Shift method'), ('Shift work', 'Shift work')], max_length=100),
        ),
    ]
