# Generated by Django 2.1.2 on 2020-05-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20200527_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Project work', 'Project work'), ('Part-time employment', 'Part-time employment'), ('Full employment', 'Full employment'), ('Volunteering', 'Volunteering')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Full day', 'Full day'), ('Shift work', 'Shift work'), ('Shift method', 'Shift method'), ('Flexible schedule', 'Flexible schedule'), ('Remote work', 'Remote work')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=12, null=True),
        ),
    ]
