# Generated by Django 2.1.2 on 2020-05-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20200530_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Part-time employment', 'Part-time employment'), ('Full employment', 'Full employment'), ('Volunteering', 'Volunteering'), ('Internship', 'Internship'), ('Project work', 'Project work')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Full day', 'Full day'), ('Remote work', 'Remote work'), ('Flexible schedule', 'Flexible schedule'), ('Shift work', 'Shift work'), ('Shift method', 'Shift method')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=12, null=True),
        ),
    ]
