# Generated by Django 2.1.2 on 2020-05-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_auto_20200531_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Part-time employment', 'Part-time employment'), ('Internship', 'Internship'), ('Project work', 'Project work'), ('Full employment', 'Full employment'), ('Volunteering', 'Volunteering')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Remote work', 'Remote work'), ('Shift work', 'Shift work'), ('Full day', 'Full day'), ('Shift method', 'Shift method'), ('Flexible schedule', 'Flexible schedule')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=12, null=True),
        ),
    ]
