# Generated by Django 2.1.2 on 2020-05-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20200531_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Part-time employment', 'Part-time employment'), ('Internship', 'Internship'), ('Volunteering', 'Volunteering'), ('Project work', 'Project work'), ('Full employment', 'Full employment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Shift work', 'Shift work'), ('Full day', 'Full day'), ('Shift method', 'Shift method'), ('Remote work', 'Remote work'), ('Flexible schedule', 'Flexible schedule')], max_length=100),
        ),
    ]
