# Generated by Django 2.1.2 on 2020-05-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_auto_20200531_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Volunteering', 'Volunteering'), ('Full employment', 'Full employment'), ('Part-time employment', 'Part-time employment'), ('Project work', 'Project work'), ('Internship', 'Internship')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Remote work', 'Remote work'), ('Shift method', 'Shift method'), ('Flexible schedule', 'Flexible schedule'), ('Full day', 'Full day'), ('Shift work', 'Shift work')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=12, null=True),
        ),
    ]
