# Generated by Django 2.1.2 on 2020-05-31 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0031_auto_20200531_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='student/uploads/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Project work', 'Project work'), ('Part-time employment', 'Part-time employment'), ('Volunteering', 'Volunteering'), ('Full employment', 'Full employment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Shift method', 'Shift method'), ('Remote work', 'Remote work'), ('Full day', 'Full day'), ('Shift work', 'Shift work'), ('Flexible schedule', 'Flexible schedule')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=12, null=True),
        ),
    ]
