# Generated by Django 2.1.2 on 2020-06-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20200601_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Project work', 'Project work'), ('Part-time employment', 'Part-time employment'), ('Full employment', 'Full employment'), ('Volunteering', 'Volunteering')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Shift work', 'Shift work'), ('Full day', 'Full day'), ('Flexible schedule', 'Flexible schedule'), ('Remote work', 'Remote work'), ('Shift method', 'Shift method')], max_length=100),
        ),
        migrations.AlterField(
            model_name='photostudent',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
