# Generated by Django 2.1.2 on 2020-06-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_auto_20200605_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Part-time employment', 'Part-time employment'), ('Internship', 'Internship'), ('Project work', 'Project work'), ('Volunteering', 'Volunteering'), ('Full employment', 'Full employment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Remote work', 'Remote work'), ('Full day', 'Full day'), ('Shift work', 'Shift work'), ('Flexible schedule', 'Flexible schedule'), ('Shift method', 'Shift method')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=12, null=True),
        ),
    ]
