# Generated by Django 2.1.2 on 2020-06-06 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0036_auto_20200605_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_photo', models.ImageField(null=True, upload_to='')),
                ('about_portfolio', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='employment',
            field=models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Volunteering', 'Volunteering'), ('Project work', 'Project work'), ('Full employment', 'Full employment'), ('Part-time employment', 'Part-time employment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Shift method', 'Shift method'), ('Full day', 'Full day'), ('Remote work', 'Remote work'), ('Flexible schedule', 'Flexible schedule'), ('Shift work', 'Shift work')], max_length=100),
        ),
    ]
